### ISSUE TITLE
What is the CheXpert-small?

### ISSUE THREAD

**Issue by Orange2107** [Stomper10/CheXpert#5]
Hi,
Can you tell me what is the CheXpert-small?
Was the smaller resolution selected on the original dataset?
Thank you

**Comment by Stomper10** [comment]
Hi,
CheXpert allows you to download both original-resolution and smaller-resolution images.
After you write a registration form, you will receive an email with the download link. 
There are two zip files you can download (439GB - original or 11GB - downsampled)
Thank you :)

**Comment by Orange2107** [comment]
Thanks for your replay.
